version: '3.8'

services:
  app:
    build: .
    container_name: ssr-app
    ports:
      - "3000:2000" # HOST:CONTAINER
    env_file:
      - config.env
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
